# Question 1
Write a NumPy program to replace the negative values in a NumPy array with 0

In [1]:
import numpy as np
a1=np.array([-1,2,0,-3,0,3,5,-7,4,0])

In [2]:
print(a1)
a1[a1<0]=0
print(a1)

[-1  2  0 -3  0  3  5 -7  4  0]
[0 2 0 0 0 3 5 0 4 0]



# Question 2

Write a NumPy program to replace all elements of a NumPy array that are greater than the
specified array.[Expected Output:
[[ 0.42436315 0.48558583 0.32924763]
[ 0.7439979 0.58220701 0.38213418]
[ 0.5097581 0.34528799 0.1563123 ]]
                 
Original array:
Replace all elements of the said array with .5 which are greater than. 5
[[ 0.42436315,0.48558583,0.32924763]
[ 0.5 ,0.5 ,0.38213418]
[ 0.5 ,0.34528799 ,0.1563123 ]]]

In [3]:
a1=np.array([[ 0.42436315,0.48558583,0.32924763],
[ 0.5 ,0.5 ,0.38213418],
[ 0.5 ,0.34528799 ,0.1563123 ]])

In [4]:
a=0.5
a1[a1>a]=0.5
a1

array([[0.42436315, 0.48558583, 0.32924763],
       [0.5       , 0.5       , 0.38213418],
       [0.5       , 0.34528799, 0.1563123 ]])

# Question 3

Write a NumPy program to convert a NumPy array into Python list structure.


In [5]:
arr=np.array([1,2,3,3,3],ndmin=0)

In [6]:
arr.tolist()

[1, 2, 3, 3, 3]


# Question 4
Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [7]:
arr1=np.arange(11)

In [8]:
np.random.permutation(arr1)

array([ 2,  3,  5,  8,  4,  9,  7,  0,  6, 10,  1])

# Question 5

                    
Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array:
(10,20,30), (40,50,60)

In [9]:
a1=np.array([10,20,30])
a2=np.array([40,50,60])

In [10]:
np.vstack((a1,a2))

array([[10, 20, 30],
       [40, 50, 60]])

# Question 6
Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

In [11]:
q1=np.array([[0, 1, 3],[5, 7, 9]])
q2=np.array([[0, 2, 4],[6, 8, 10]])


In [12]:
np.concatenate((q1,q2),axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

# Question 7
Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.
# ASK SIR

In [41]:
a1=np.zeros((5,5))
a1
a1.shape

(5, 5)

In [39]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [47]:
a1=a1+x
a1.shape

(5, 5)

# Question 8
Write a NumPy program to move axes of an array to new positions. Other axes remain in
their original order. [Expected Output:
(3, 4, 2)
(4, 2, 3)]

# ASK SIR

In [48]:
arr1=np.array([3,4,2])
arr2=np.array([4,2,3])

In [51]:
x=np.zeros((2,3,4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.moveaxis()

# Question 9
Write a NumPy program to view inputs as arrays with at least two dimensions, three
dimensions.

In [17]:
a1=np.array([1,2,3])

In [18]:
np.atleast_2d(a1)

array([[1, 2, 3]])

In [19]:
np.atleast_3d(a1)

array([[[1],
        [2],
        [3]]])


# Question 10

Write a NumPy program to create a 4x4 array, now create a new array from the said array
swapping first and last, second and third columns.
# ask to explain stepping


In [20]:
q1=np.arange(16).reshape(4,4)

In [21]:
q1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
newq1=q1[ : , ::-1]

In [23]:
newq1

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

# Question 11


Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [24]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])

In [25]:
np.multiply(a1,a2)

array([ 4, 10, 18])

# Question 12

Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros
on the main diagonal.
# Ask Stepping


In [26]:
a1=np.ones((4,4))

In [53]:
a1[ : , ::2]=0
a1

array([[ 0.,  5.,  0., 15.,  0.],
       [ 0.,  5.,  0., 15.,  0.],
       [ 0.,  5.,  0., 15.,  0.],
       [ 0.,  5.,  0., 15.,  0.],
       [ 0.,  5.,  0., 15.,  0.]])

In [58]:
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]



# Question 13
Write a NumPy program to create a 3x3 identity matrix

In [28]:
arr1=np.identity(3)

In [29]:
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Question 14

Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.


In [30]:
a1=np.ones(10)

In [31]:
a1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
a2=np.zeros(10)

In [33]:
a2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
a3=np.full(10,5)

In [35]:
a3

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# Question 15
Write a NumPy program to get help on the add function.

In [36]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [1]:
pip install nbconvert


In [6]:
sudo install pandoc


SyntaxError: invalid syntax (1333997014.py, line 1)